# Generated by Django 5.2.7 on 2026-01-20 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('geburtsjahr', models.IntegerField()),
                ('verein', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('einheit', models.CharField(max_length=20)),
                ('gewichtung', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kari1', models.FloatField()),
                ('kari2', models.FloatField()),
                ('kari3', models.FloatField()),
                ('kari4', models.FloatField()),
                ('kari5', models.FloatField()),
                ('awert', models.FloatField()),
                ('ewert', models.FloatField()),
                ('dwert', models.FloatField()),
                ('score', models.FloatField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.competition')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.discipline')),
            ],
        ),
    ]
