# Generated by Django 5.2.7 on 2026-01-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp_Dis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.FloatField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.competition')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.discipline')),
            ],
        ),
    ]
