# Generated by Django 5.2.7 on 2026-01-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_comp_dis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete_Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.competition')),
            ],
        ),
    ]
