# Generated by Django 5.2.7 on 2026-01-23 23:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grading',
            name='awert',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='kari2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='kari3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='kari4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grading',
            name='kari5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.CharField(max_length=500)),
                ('log_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.athlete')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.competition')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
