# Generated by Django 5.2.7 on 2026-01-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_alter_grading_awert_alter_grading_kari2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
