# Generated by Django 5.2.7 on 2026-02-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_logs_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='dbid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete_comp',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athlete_comp',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
