# Generated by Django 5.2.7 on 2026-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_athlete_dbid_athlete_comp_ranking_athlete_comp_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='vier_aus_sechs',
            field=models.BooleanField(default=False),
        ),
    ]
