# Generated by Django 5.2.7 on 2026-04-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0008_competition_vier_aus_sechs'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='riege',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
