# Generated by Django 5.2.7 on 2026-05-26 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_athlete_riege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mannschaft',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('verein', models.CharField(max_length=100)),
                ('mannschaftsnr', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='mannschaftsid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Mannschaft_Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abzug', models.FloatField(default=0)),
                ('score_day1', models.FloatField(blank=True, null=True)),
                ('score_day2', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.competition')),
                ('mannschaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.mannschaft')),
            ],
        ),
        migrations.CreateModel(
            name='Mannschaft_Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('day', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.competition')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.discipline')),
                ('mannschaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.mannschaft')),
            ],
        ),
    ]
