# Generated by Django 5.2.7 on 2026-05-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0010_mannschaft_athlete_mannschaftsid_mannschaft_comp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='mannschaftsid',
        ),
        migrations.AddField(
            model_name='athlete',
            name='mannschaft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grading.mannschaft'),
        ),
    ]
