# Generated by Django 5.2.7 on 2026-05-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0011_remove_athlete_mannschaftsid_athlete_mannschaft'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='ak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='athlete_comp',
            name='score2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
