# Generated by Django 5.2.7 on 2026-05-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_athlete_ak_athlete_comp_score2'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mannschaft_grading',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
