# Generated by Django 5.2.7 on 2026-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0013_grading_day_alter_mannschaft_grading_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannschaft',
            name='dbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
